name: SimpleChatBubbles
version: '${version}'
main: org.lushplugins.simplechatbubbles.SimpleChatBubbles
api-version: '1.20'
dependencies:
  server:
    FancyHolograms:
      load: BEFORE
      required: true
    packetevents:
      load: BEFORE
      required: true