name: SimpleChatBubbles
version: '${version}'
main: org.lushplugins.simplechatbubbles.SimpleChatBubbles
api-version: '1.20'
depend:
  - FancyHolograms
  - packetevents
commands:
  chatbubbles:
    description: Main command for SimpleChatBubbles
    usage: /<command>
    aliases: [cb, chatb]