name: SimpleChatBubbles
version: '${version}'
main: me.dave.simplechatbubbles.SimpleChatBubbles
api-version: '1.20'
depend:
  - FancyHolograms
commands:
  chatbubbles:
    description: Main command for SimpleChatBubbles
    usage: /<command>
    aliases: [cb, chatb]